### ISSUE TITLE
可以把 sysconfig 等子 crate 发布到 crates.io 上面吗

### ISSUE THREAD

**Issue by gfreezy** [LuoZijun/exodus#28]

**Comment by LuoZijun** [comment]
`sysconfig` 其实没有完成，它依赖 `netlink` 等 `crate`。总的来说希望它能担任一个系统配置的角色。不再依赖命令行调用。

*  route add/del/get ...
*  ip link/neigh/addr list/get/set/del
*  dns set/get
*  sysctl net.ipv4.conf.all.forwarding = 1
*  firewall add/del  (iptables/nftables/pfctl)

目前 `防火墙` 这部分是没有写的，其余的大概都差不多了。所以可能现在还不适合发布。

**Comment by gfreezy** [comment]
我看cargo是支持你sub crate git依赖的，但是 sysconfig 用不了，这个是需要加什么配置吗

https://github.com/rust-lang/cargo/issues/1466

**Comment by LuoZijun** [comment]
当前的代码都是在 `rewrite` 分支上，所以你可能需要这样使用:

Cargo.toml
```toml
[package]
name = "sysctl_example"
version = "0.1.0"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysctl = { git = "https://github.com/ExodusVPN/exodus", branch = "rewrite" }
```

src/main.rs
```rust
extern crate sysctl;

use std::io;

fn walk() -> Result<(), io::Error> {
    let root = sysctl::Mib::default();
    for item in root.iter()? {
        let mib = item?;
        println!("{}", mib.name()?);
    }
    Ok(())
}

fn main() -> Result<(), io::Error> {
    walk()
}
```
